### ISSUE TITLE
(Python) Getting unrecognized argument --no-led-hardware-pulse

### ISSUE THREAD

**Issue by Gariantroll** [hzeller/rpi-rgb-led-matrix#249]
I am getting this error.  I tried to blacklist the sound, but I am still getting this error

runtext.py: error: unrecognized arguments: --led-no-hardware-pulse

**Comment by hzeller** [comment]
Yes, this is expected, the Python library does not use the flags yet. Pull requests that change that welcome.

**Comment by Gariantroll** [comment]
I got rid of the audio file and it worked.  Thanks for your help and quick responses.

**Comment by hzeller** [comment]
Getting rid of the audio is the best solution anyway.

In the latest commit https://github.com/hzeller/rpi-rgb-led-matrix/commit/e2ffd91644eb9ca36b57921c07106be1ef0d0f63 the lack of options has been fixed, and there is now a `--led-no-hardware-pulse`

**Comment by tomsepe** [comment]
Hello, It seems this error is back. I have a raspberrypi 4 and just downloaded the files using the script provided by adafruit's tutorial. and when I try to run runtext.py with the "--led-no-hardware-pulse" I get the "expected one argument response"
